# Generated by Django 3.2.4 on 2021-06-11 03:46

from django.db import migrations, models

from owela.core.game import new_board


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.IntegerField(
                        choices=[(1, "In Progress"), (2, "Finished")], default=1
                    ),
                ),
                (
                    "next_turn",
                    models.IntegerField(choices=[(1, "Human"), (2, "Ai")], default=1),
                ),
                (
                    "winner",
                    models.IntegerField(choices=[(1, "Human"), (2, "Ai")], null=True),
                ),
                ("board", models.JSONField(default=new_board)),
            ],
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                check=models.Q(("state__in", [1, 2])), name="core_game_state_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                check=models.Q(("next_turn__in", [1, 2])),
                name="core_game_next_turn_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("winner__isnull", True), ("winner__in", [1, 2]), _connector="OR"
                ),
                name="core_game_winner_valid",
            ),
        ),
    ]
