# Generated by Django 3.2.4 on 2021-06-11 05:29

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owela_club", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="game",
            name="core_game_state_valid",
        ),
        migrations.RemoveConstraint(
            model_name="game",
            name="core_game_winner_valid",
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("state", 1), ("winner__isnull", True)),
                    models.Q(("state", 2), ("winner__in", [1, 2])),
                    _connector="OR",
                ),
                name="core_game_state",
            ),
        ),
    ]
